title: "Michael Nguyen"
author: "Michael Nguyen"
description: "My blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "MichaelNg.pdf", title:"Resume", icon:home}
  - {title: "Automated Game Bot", url:""}
  - {title: "Spotify Music Controller", url:""}
  - {title: "Discord Music Bot", url:""}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:mnguyen4527@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/mnguyen64"}
  - {title: LinkedIn, icon: linkedin-in, url: "linkedin.com/in/mnguyen64"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
